#!/usr/bin/env python2
import rospy
from geometry_msgs.msg import Twist

_twist_publisher = rospy.Publisher('cmd_vel_mux/input/teleop', Twist)

def forward(x=.5):
	move(x, 0)

def right(z=.5):
	move(0, z)

def left(z=.5):
	move(0, z)

def backward(x=.5):
	move(x, 0)

def move(x, z):
	twist = Twist()
	twist.linear.x = x
	twist.angular.z = z
	rospy.loginfo("Move({}, {})".format(x, z))
	_twist_publisher.publish(twist)
