#!/usr/bin/env python2

import pexpect
import time

class Speech_Manager(object):
	def __init__(self):
		self.espeak = pexpect.spawn('espeak -s 60') # 60 words per minute
		self.last_time = time.time() % 3600
	def speak(self, phrase):
		now = time.time() % 3600
		if now - self.last_time > 65:
			self.espeak.sendline(phrase)
			self.last_time = time.time() + 65 % 3600
