#!/usr/bin/env python2


# python default modules
import subprocess
import sys
import time

# ROS specifoc
import roslib; roslib.load_manifest('mazeDancing')
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import Float64MultiArray

# opencv and simplecv modules
import cv
import cv2.cv as cv
from cv_bridge import CvBridge, CvBridgeError
import SimpleCV

# my modules
import detectDrone

g_detector = None
g_publisher = None

# ROS loop
def main(argv=None):
	if argv is None:
		argv = sys.argv

	rospy.init_node('startDrone')
	rospy.loginfo(DEBUG_STRING + "startDrone has initialized")

	depth_sub = rospy.Subscriber('/camera/depth/image_raw', Image, depthCallback, queue_size=1)
	color_sub = rospy.Subscriber('/camera/rgb/image_color', Image, colorCallback, queue_size=1)
	rospy.spin()

if __name__ == "__main__":
	try:
		sys.exit(main())
	except rospy.ROSInterruptException:
		pass
