#!/usr/bin/env python2

import time
import sys

# ROS specifoc
import rospy

# my modules
from Speech  import *
from Sensor_Manager  import *
from Move_Manager  import *

def pcl(speech, sensor, move):
	rospy.loginfo("FULL: " + str(sensor.full_pcl()))
	rospy.loginfo("RIGHT BIAS: " + str(sensor.bias_pcl(Direction.RIGHT)))
	rospy.loginfo("LEFT BIAS: " + str(sensor.bias_pcl(Direction.LEFT)))

def depth(speec, sensor, move):
	rospy.loginfo("FULL: " + str(sensor.full_depth()))

# ROS loop
def main(speech, sensor, move):
	controls = (speech, sensor, move)
	while not rospy.is_shutdown():
		pcl(*controls)

if __name__ == "__main__":

	try:
		speech = Speech_Manager()
		sensor = Sensor_Manager()
		move = Move_Manager(sensor, z=1)
		speech.speak("booting up")
		sys.exit(main(speech, sensor, move))
	except rospy.ROSInterruptException:
		pass
