#!/usr/bin/env python2

import time
import sys

# ROS specifoc
import rospy

# my modules
from Speech  import *
from Sensor_Manager  import *
from Move_Manager  import *

# ROS loop
def main(speech, sensor, move):
	controls = (speech, sensor, move)
	while not rospy.is_shutdown():
		rospy.loginfo(sensor.read_depth())
		rospy.Rate(1).sleep()

if __name__ == "__main__":
	try:
		speech = Speech_Manager()
		sensor = Sensor_Manager()
		move = Move_Manager(sensor, z=1)
		speech.speak("booting up")
		time.sleep(1)
		sys.exit(main(speech, sensor, move))
	except rospy.ROSInterruptException:
		pass
