#!/usr/bin/env python2

import time
import sys

# ROS specifoc
import rospy

# my modules
from Move_Manager  import *
from Dance import *

def fixed_path(move):
	path = [Direction.LEFT, Direction.RIGHT, Direction.FORWARD]
	do_dance(path, move)

def detect_path():
	print(interpret_dance())

# ROS loop
def main(move):
	fixed_path(move)
	# detect_path()
	return 

if __name__ == "__main__":
	try:
		rospy.init_node('test_dance')
		move = Move_Manager()
		time.sleep(1)
		sys.exit(main(move))
	except rospy.ROSInterruptException:
		pass
