#!/usr/bin/env python2

import time
import sys

# ROS specifoc
import rospy

# my modules
from Speech  import *
from Move_Manager  import *

def doCircle(speech, move):
	speech.speak("do circle")
	move.move(Direction.LEFT)
	speech.speak("now backward")
	move.move(Direction.RIGHT)

# ROS loop
def main(speech, move):
	controls = (speech, move)
	while not rospy.is_shutdown():
		forward_backward(*controls)
	return 

if __name__ == "__main__":
	try:
		rospy.init_node('practice movements')
		speech = Speech_Manager()
		speech.speak("booting up")
		move = Move_Manager(z=1)
		time.sleep(1)
		sys.exit(main(speech, sensor, move))
	except rospy.ROSInterruptException:
		pass
