#!/usr/bin/env python2

import time

# ROS specifoc
import rospy

# my modules
import Sensor_Manager
import Move_Manager
import Speech

# ROS loop
def main(argv=None):
	speech = Speech_Manager()
	speech.speak("booting up")
	sensor = Sensor_Manager()
	move = Move_Manager(sensor)
	while True:
		move.turn_right()
		time.sleep(1)
		speech.speak("turned")
	rospy.spin()

if __name__ == "__main__":
	try:
		sys.exit(main())
	except rospy.ROSInterruptException:
		pass
