#!/usr/bin/env python2

import time
import sys

# ROS specifoc
import rospy

# my modules
from Move_Manager  import *
from consts import *


# ROS loop
def main(move):
	move.move(Direction.FORWARD)
	return
	for _ in range(5):
		move.move(Direction.LEFT)
		move.move(Direction.RIGHT)
		move.move(Direction.RIGHT)
		move.move(Direction.LEFT)
	time.sleep(5)

if __name__ == "__main__":
	try:
		rospy.init_node('practice_movements')
		move = Move_Manager()
		sys.exit(main(move))
	except rospy.ROSInterruptException:
		pass
