#!/usr/bin/env python2

import pexpect
import sys
import time
from consts import *
import rospy
from std_msgs.msg import String

# wrap pexpect
class Speech_Manager(object):
	def __init__(self):
		self.node = rospy.init_node(SPEECH_NODE)
		self.espeak = pexpect.spawn('espeak') 
		self._sub = rospy.Subscriber(SPEECH_IO, String, self.speak)

	def speak(self, phrase):
		phrase = str(phrase.data)
		print(phrase)
		self.espeak.sendline(phrase)

def main():
	sm = Speech_Manager()
	r = rospy.Rate(1)
	while not rospy.is_shutdown():
		r.sleep()

if __name__ == "__main__":
	try:
		sys.exit(main())
	except rospy.ROSInterruptException:
		pass
