#!/usr/bin/env python2

from Maze import *

m = Maze()
m.step()
m.turn(Direction.RIGHT)
m.step()
m.step()
m.turn(Direction.LEFT)
m.turn(Direction.LEFT)
m.step()
m.turn(Direction.RIGHT)
m.step()
m.print_maze()
sc, wo = m.best_path()
print(sc)
print(wo)
